function par_smoothfuncs(subpar)
% function par_smoothfuncs(subpar)
% smooth functional images
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% 
% written by jbh
% modified by amg

origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end



fprintf('---Smoothing for %s---\n',par.substr);

allwascanfiles = par.allwascanfiles;
Sn     = size(allwascanfiles,1);

% forloop taken from spm_config_smooth 
for i = 1:Sn
    Q = deblank(allwascanfiles(i,:));
    [pth,nam,xt,nm] = spm_fileparts(deblank(Q));
    U = fullfile(pth,['s' nam xt nm]);
    spm_smooth(Q,U,par.smoothkernel);
end

fprintf('---Smoothing COMPLETED for %s---\n',par.substr);

cd(origdir);