function par_normfuncs(subpar)
% function par_normfuncs(subpar)
% normalize functionals
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% 
% written by jbh
% modified by amg

origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end


fprintf('---Normalizing funcs for Subject %d---\n',par.subnum);

graywrimg = par.graywrimg;
grwrflags = par.grwrflags;
[grpth,grnm] = fileparts(graywrimg);
grmatname        = fullfile(grpth,[grnm '_sn.mat']);
allascanfiles = par.allascanfiles;
spm_write_sn(allascanfiles, grmatname,grwrflags);

fprintf('---Normalizing funcs COMPLETED for Subject %d---\n',par.subnum);


cd(origdir);